services:
  webserver:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 8082:80
    volumes:
      - ${CAMERA_RECORDINGS}:/app/camera-recordings
    environment:
      - PASSWORD=${PASSWORD}
    restart: always
